# Generated by Django 5.2 on 2026-02-02 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0052_servicetype_delete_payment_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [

        # Remove old email field
        migrations.RemoveField(
            model_name='payment',
            name='email',
        ),

        # Store application ID (generic reference) — allow null initially
        migrations.AddField(
            model_name='payment',
            name='application_id',
            field=models.PositiveIntegerField(
                null=True,
                blank=True,
            ),
        ),

        # Store application model name — allow null initially
        migrations.AddField(
            model_name='payment',
            name='application_model',
            field=models.CharField(
                max_length=100,
                null=True,
                blank=True,
            ),
        ),

        # Link payment to service type — allow null initially
        migrations.AddField(
            model_name='payment',
            name='service_type',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='certificates.servicetype',
            ),
        ),

        # Reference stays UUID-based
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),

        # Status stays clean
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('SUCCESS', 'Success'),
                    ('FAILED', 'Failed'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
    ]
