# Generated by Django 5.2 on 2025-05-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateapplication',
            name='method_of_payment',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('debit_credit_card', 'Debit/Credit Card'), ('bank_deposit', 'Direct Bank Deposit')], default='mobile_money', max_length=50, verbose_name='How do you intend to proceed with required payments for this application?'),
        ),
    ]
