# Generated by Django 5.2 on 2025-05-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificateapplication_method_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateapplication',
            name='number_of_drinking_water_facilities',
            field=models.CharField(choices=[('none', 'None'), ('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('more than three', 'More than Three')], max_length=20),
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='number_of_gender_sensitive_latrines',
            field=models.CharField(choices=[('none', 'None'), ('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('more than three', 'More than Three')], max_length=20),
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='number_of_handwashing_facilities',
            field=models.CharField(choices=[('none', 'None'), ('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('more than three', 'More than Three')], max_length=20),
        ),
    ]
