# Generated by Django 5.2 on 2025-05-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificateapplication_number_of_drinking_water_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateapplication',
            name='name_of_banks',
            field=models.CharField(blank=True, choices=[('IB', 'IB'), ('EcoBank', 'EcoBank'), ('GT Bank', 'GT Bank'), ('Afriland First Bank', 'Afriland First Bank'), ('LBDI Bank', 'LBDI Bank'), ('SIB Bank', 'SIB Bank'), ('Bloom Bank', 'Bloom Bank'), ('UBA Bank', 'UBA Bank')], max_length=50, null=True),
        ),
    ]
