# Generated by Django 5.2 on 2025-05-09 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_certificateapplication_name_of_banks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseapplication',
            name='entity_name',
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.partner'),
        ),
    ]
