# Generated by Django 5.2 on 2025-05-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_remove_licenseapplication_entity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='generated_license',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
