# Generated by Django 5.2 on 2025-05-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_licenseapplication_generated_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='certificate_type',
            field=models.CharField(default='Permit', max_length=255),
            preserve_default=False,
        ),
    ]
