# Generated by Django 5.2 on 2025-05-09 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_licenseapplication_certificate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='application_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
