# Generated by Django 5.2 on 2025-05-09 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_licenseapplication_application_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceapplication',
            name='ngo_name',
        ),
        migrations.AddField(
            model_name='clearanceapplication',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.partner'),
        ),
    ]
