# Generated by Django 5.2 on 2025-05-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_remove_clearanceapplication_ngo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceapplication',
            name='generated_clearance',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
