# Generated by Django 5.2 on 2025-05-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_clearanceapplication_generated_clearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceapplication',
            name='certificate_type',
            field=models.CharField(default='certificate', max_length=255),
            preserve_default=False,
        ),
    ]
