# Generated by Django 5.2 on 2025-05-09 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0011_clearanceapplication_certificate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscertificateapplication',
            name='name_of_entity',
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.partner'),
        ),
    ]
