# Generated by Django 5.2 on 2025-05-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0012_remove_businesscertificateapplication_name_of_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='generated_business_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
