# Generated by Django 5.2 on 2025-05-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0013_businesscertificateapplication_generated_business_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='certificate_type',
            field=models.CharField(default='certificate', max_length=255),
            preserve_default=False,
        ),
    ]
