# Generated by Django 5.2 on 2025-05-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0014_businesscertificateapplication_certificate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='b_certificate_payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='business_certificates/docs/'),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='certificate_payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='certificates/documents/business_registration/'),
        ),
        migrations.AddField(
            model_name='clearanceapplication',
            name='clearance_payment_receipt',
            field=models.FileField(default='receipt', upload_to='clearance/supporting_docs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='license_payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='license/supporting_docs/'),
        ),
    ]
