# Generated by Django 5.2 on 2025-05-13 14:44

import certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0015_businesscertificateapplication_b_certificate_payment_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateapplication',
            name='expiry_date',
            field=models.DateField(default=certificates.models.default_expiry_date),
        ),
    ]
