# Generated by Django 5.2 on 2025-05-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0016_certificateapplication_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateapplication',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='tin_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
