# Generated by Django 5.2 on 2025-05-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0017_certificateapplication_certificate_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateapplication',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='tin_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
