# Generated by Django 5.2 on 2025-05-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0018_remove_certificateapplication_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceapplication',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clearanceapplication',
            name='tin_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='tin_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
