# Generated by Django 5.2 on 2025-05-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0019_clearanceapplication_certificate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='submitted_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
