# Generated by Django 5.2 on 2025-05-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0020_alter_licenseapplication_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='ceo_approved_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='compliance_approved_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='ed_approved_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
