# Generated by Django 5.2 on 2025-05-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0021_alter_licenseapplication_ceo_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='banks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
