# Generated by Django 5.2 on 2025-06-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0022_alter_licenseapplication_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='cv_of_staff_3',
            field=models.FileField(blank=True, null=True, upload_to='business_certificates/cvs/'),
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='education_experience_of_staff_3',
            field=models.TextField(default='Postgraduate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='name_of_staff_3',
            field=models.CharField(default='Fitzgerald Challar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='nationality_of_staff_3',
            field=models.CharField(default='Liberian', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='position_of_staff_3',
            field=models.CharField(default='Technical Assistant', max_length=100),
            preserve_default=False,
        ),
    ]
