# Generated by Django 5.2 on 2025-06-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0023_businesscertificateapplication_cv_of_staff_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscertificateapplication',
            name='education_experience_of_staff_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscertificateapplication',
            name='education_experience_of_staff_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscertificateapplication',
            name='name_of_staff_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businesscertificateapplication',
            name='name_of_staff_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businesscertificateapplication',
            name='nationality_of_staff_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businesscertificateapplication',
            name='nationality_of_staff_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businesscertificateapplication',
            name='position_of_staff_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businesscertificateapplication',
            name='position_of_staff_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
