# Generated by Django 5.2 on 2025-06-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0024_alter_businesscertificateapplication_education_experience_of_staff_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateapplication',
            name='admin_staff_2_cv',
            field=models.FileField(blank=True, null=True, upload_to='certificates/admin_staff_1/cv/'),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='admin_staff_2_education',
            field=models.CharField(blank=True, choices=[('High School Graduate', 'High School Graduate'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('PhD', 'PhD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='admin_staff_2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='admin_staff_2_nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='admin_staff_2_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='admin_staff_2_work_permit',
            field=models.FileField(blank=True, null=True, upload_to='certificates/admin_staff_1/work_permit/'),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='admin_staff_2_years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='admin_staff_3_cv',
            field=models.FileField(blank=True, null=True, upload_to='certificates/admin_staff_1/cv/'),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='admin_staff_3_education',
            field=models.CharField(blank=True, choices=[('High School Graduate', 'High School Graduate'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('PhD', 'PhD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='admin_staff_3_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='admin_staff_3_nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='admin_staff_3_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='admin_staff_3_work_permit',
            field=models.FileField(blank=True, null=True, upload_to='certificates/admin_staff_1/work_permit/'),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='admin_staff_3_years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
