# Generated by Django 5.2 on 2025-06-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0025_certificateapplication_admin_staff_2_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateapplication',
            name='certificate_payment_receipt',
            field=models.FileField(default='Certificate Payment Receipt', upload_to='certificates/documents/business_registration/'),
            preserve_default=False,
        ),
    ]
