# Generated by Django 5.2 on 2025-06-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0026_alter_certificateapplication_certificate_payment_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='staff_cv',
            new_name='staff_cv_1',
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='staff_education',
            new_name='staff_education_1',
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='staff_experience_years',
            new_name='staff_experience_years_1',
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='staff_name',
            new_name='staff_name_1',
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='staff_nationality',
            new_name='staff_nationality_1',
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='staff_position',
            new_name='staff_position_1',
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='staff_work_permit',
            new_name='staff_work_permit_1',
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='staff_cv_2',
            field=models.FileField(blank=True, null=True, upload_to='license/cv/'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='staff_cv_3',
            field=models.FileField(blank=True, null=True, upload_to='license/cv/'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='staff_education_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='staff_education_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='staff_experience_years_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='staff_experience_years_3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='staff_name_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='staff_nationality_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='staff_nationality_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='staff_position_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='staff_position_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='staff_work_permit_2',
            field=models.FileField(blank=True, null=True, upload_to='license/work_permits/'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='staff_work_permit_3',
            field=models.FileField(blank=True, null=True, upload_to='license/work_permits/'),
        ),
    ]
