# Generated by Django 5.2 on 2025-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0027_rename_staff_cv_licenseapplication_staff_cv_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='staff_name_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
