# Generated by Django 5.2 on 2025-06-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0028_licenseapplication_staff_name_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='business_registration',
            field=models.FileField(default='business registration', upload_to='license/supporting_docs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='license_payment_receipt',
            field=models.FileField(default='license receipt', upload_to='license/supporting_docs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='water_quality_report',
            field=models.FileField(default='water quality report', upload_to='license/supporting_docs/'),
            preserve_default=False,
        ),
    ]
