# Generated by Django 5.2 on 2025-06-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0029_alter_licenseapplication_business_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateapplication',
            name='certificate_type',
        ),
        migrations.RemoveField(
            model_name='licenseapplication',
            name='certificate_type',
        ),
    ]
