# Generated by Django 5.2 on 2025-06-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0030_remove_certificateapplication_certificate_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceapplication',
            name='certificate_type',
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='additional_equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='casting_yard',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='chain_block',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='culvert_mould',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='light_vehicles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='pickups_4wd',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project1_funding_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project1_implementation_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project1_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project2_funding_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project2_implementation_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project2_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project3_funding_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project3_implementation_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project3_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project3_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project4_funding_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project4_implementation_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project4_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='project4_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='pulley',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='rig_compressor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='size_0_76m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='size_0_90m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='sub_office_addresses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='tripod',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
