# Generated by Django 5.2 on 2025-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0031_remove_clearanceapplication_certificate_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearanceapplication',
            old_name='approved_me_report',
            new_name='business_registration_and_tax_clearance',
        ),
        migrations.RenameField(
            model_name='clearanceapplication',
            old_name='water_quality_and_turnover_docs',
            new_name='letter_of_application',
        ),
        migrations.AddField(
            model_name='clearanceapplication',
            name='organization_profile',
            field=models.FileField(blank=True, null=True, upload_to='clearance/supporting_docs/'),
        ),
        migrations.AddField(
            model_name='clearanceapplication',
            name='previous_year_activities_report',
            field=models.FileField(default='activities report', upload_to='clearance/supporting_docs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='approved_wash_workplan',
            field=models.FileField(blank=True, null=True, upload_to='clearance/supporting_docs/'),
        ),
    ]
