# Generated by Django 5.2 on 2025-06-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0032_rename_approved_me_report_clearanceapplication_business_registration_and_tax_clearance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceapplication',
            name='casting_yard',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='chain_block',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='culvert_mould',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='light_vehicles',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='pickups_4wd',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='pulley',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='rig_compressor',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='size_0_76m',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='size_0_90m',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='tripod',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
