# Generated by Django 5.2 on 2025-06-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0033_alter_clearanceapplication_casting_yard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='tax_clearance',
            field=models.FileField(default='tax clearance', upload_to='license/supporting_docs/'),
            preserve_default=False,
        ),
    ]
