# Generated by Django 5.2 on 2025-06-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0034_alter_licenseapplication_tax_clearance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='quality_analysis_report',
            new_name='letter_of_application',
        ),
    ]
