# Generated by Django 5.2 on 2025-06-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0035_rename_quality_analysis_report_licenseapplication_letter_of_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificateapplication',
            old_name='accreditation_moe',
            new_name='letter_of_application',
        ),
        migrations.RemoveField(
            model_name='businesscertificateapplication',
            name='accreditation_from_lmhra',
        ),
        migrations.RemoveField(
            model_name='businesscertificateapplication',
            name='certificate_type',
        ),
        migrations.RemoveField(
            model_name='businesscertificateapplication',
            name='permit_from_micat',
        ),
        migrations.RemoveField(
            model_name='certificateapplication',
            name='accreditation_lmhra',
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='letter_of_application',
            field=models.FileField(default='letter of application', upload_to='business_certificates/docs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='information_sheet',
            field=models.FileField(default='information sheet', upload_to='certificates/documents/accreditation_lmhra/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesscertificateapplication',
            name='b_certificate_payment_receipt',
            field=models.FileField(default='certificate payment receipt', upload_to='business_certificates/docs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='business_registration',
            field=models.FileField(default='business registration', upload_to='certificates/documents/business_registration/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='letter_of_application',
            field=models.FileField(default='letter of application', upload_to='license/supporting_docs/'),
            preserve_default=False,
        ),
    ]
