# Generated by Django 5.2 on 2025-06-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0036_rename_accreditation_moe_certificateapplication_letter_of_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscertificateapplication',
            name='letter_of_application',
            field=models.FileField(blank=True, null=True, upload_to='business_certificates/docs/'),
        ),
    ]
