# Generated by Django 5.2 on 2025-06-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0037_alter_businesscertificateapplication_letter_of_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateapplication',
            name='admin_staff_2_cv',
            field=models.FileField(blank=True, null=True, upload_to='certificates/admin_staff_2/cv/'),
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='admin_staff_2_work_permit',
            field=models.FileField(blank=True, null=True, upload_to='certificates/admin_staff_2/work_permit/'),
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='admin_staff_3_cv',
            field=models.FileField(blank=True, null=True, upload_to='certificates/admin_staff_3/cv/'),
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='admin_staff_3_work_permit',
            field=models.FileField(blank=True, null=True, upload_to='certificates/admin_staff_3/work_permit/'),
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='certificate_payment_receipt',
            field=models.FileField(upload_to='certificates/documents/certificate_payment_receipt/'),
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='information_sheet',
            field=models.FileField(upload_to='certificates/documents/information_sheet/'),
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='letter_of_application',
            field=models.FileField(blank=True, null=True, upload_to='certificates/documents/letter_of_application/'),
        ),
    ]
