# Generated by Django 5.2 on 2025-06-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0038_alter_certificateapplication_admin_staff_2_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateapplication',
            name='partner',
            field=models.CharField(default='Levi C. Williams', max_length=255),
            preserve_default=False,
        ),
    ]
