# Generated by Django 5.2 on 2025-06-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0039_alter_certificateapplication_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscertificateapplication',
            name='partner',
            field=models.CharField(default='SCSS', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='partner',
            field=models.CharField(default='SCSS', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='partner',
            field=models.CharField(default='SCSS', max_length=255),
            preserve_default=False,
        ),
    ]
