# Generated by Django 5.2 on 2025-06-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0040_alter_businesscertificateapplication_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='partner',
            field=models.CharField(max_length=255),
        ),
    ]
