# Generated by Django 5.2 on 2025-06-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0041_alter_certificate_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='application',
        ),
    ]
