# Generated by Django 5.2 on 2025-07-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0042_remove_certificate_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateapplication',
            name='year_of_establishment',
        ),
    ]
