# Generated by Django 5.2 on 2025-07-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0043_remove_certificateapplication_year_of_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceapplication',
            name='casting_yard',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='chain_block',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='culvert_mould',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='light_vehicles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='pickups_4wd',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='pulley',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='rig_compressor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='size_0_76m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='size_0_90m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='tripod',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
