# Generated by Django 5.2 on 2025-07-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0044_alter_clearanceapplication_casting_yard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceapplication',
            name='application_date',
        ),
    ]
