# Generated by Django 5.2 on 2025-07-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0045_remove_clearanceapplication_application_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceapplication',
            name='year_established_in_liberia',
        ),
    ]
