# Generated by Django 5.2 on 2025-07-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0046_remove_clearanceapplication_year_established_in_liberia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscertificateapplication',
            name='year_of_establishment',
        ),
    ]
