# Generated by Django 5.2 on 2025-09-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0047_remove_businesscertificateapplication_year_of_establishment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'WCC, WC, WL - Certificates', 'verbose_name_plural': 'WCC, WC, WL - Certficates'},
        ),
        migrations.AlterModelOptions(
            name='certificateapplication',
            options={'verbose_name': 'WASH-in-School Applications', 'verbose_name_plural': 'WASH-in-School Applications'},
        ),
        migrations.AddField(
            model_name='clearanceapplication',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=650, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=650, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
