# Generated by Django 5.2 on 2025-09-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0048_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceapplication',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
