# Generated by Django 5.2 on 2026-01-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0049_clearanceapplication_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscertificateapplication',
            options={'verbose_name': 'Business Certificate Applications', 'verbose_name_plural': 'Business Certificate Applications'},
        ),
        migrations.AlterModelOptions(
            name='clearanceapplication',
            options={'verbose_name': 'Clearance Applications', 'verbose_name_plural': 'Clearance Applications'},
        ),
        migrations.AlterModelOptions(
            name='licenseapplication',
            options={'verbose_name': 'License Applications', 'verbose_name_plural': 'License Applications'},
        ),
    ]
