# Generated by Django 5.2 on 2026-02-02 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0051_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('fee', models.DecimalField(max_digits=10, decimal_places=2)),
            ],
        ),

        migrations.DeleteModel(
            name='Payment',
        ),

        migrations.AddField(
            model_name='businesscertificateapplication',
            name='service_type',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='business_certificate_applications',
                to='certificates.servicetype',
            ),
        ),

        migrations.AddField(
            model_name='certificateapplication',
            name='service_type',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='wash_applications',
                to='certificates.servicetype',
            ),
        ),

        migrations.AddField(
            model_name='clearanceapplication',
            name='service_type',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='clearance_applications',
                to='certificates.servicetype',
            ),
        ),

        migrations.AddField(
            model_name='licenseapplication',
            name='service_type',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='license_applications',
                to='certificates.servicetype',
            ),
        ),
    ]
