# Generated by Django 5.2 on 2026-02-02 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0052_servicetype_delete_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscertificateapplication',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_certificate_applications', to='certificates.servicetype'),
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wash_applications', to='certificates.servicetype'),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clearance_applications', to='certificates.servicetype'),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='license_applications', to='certificates.servicetype'),
        ),
    ]
